title: J. Edgar H. Cancino
logo: "/images/pp.jpg?raw=true"
description: >
  <br><big><b>About</b></big><br>
  B.Sc. in Robotics and Digital Systems Engineering 
  <small><br>
  Tecnologico de Monterrey (June, 2024)</small>

  <p style="margin: 0;"><big><b>Programming languages</b></big></p>
   <ul style="margin-top: 0;">
   <li>Python (3+ years)</li>
   <li>C++  (3+ years)</li>
   <li>C  (2+ years)</li>
   <li>Matlab  (2+ years)</li>
   </ul>
   </small>
   <a href="https://edgarcancinoe.github.io/pdf/Jose_Hernandez_Resume.pdf">View My Resume</a>  
   <br><br>
  <a href="https://www.linkedin.com/in/edgar-cancino/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
