title: J. Edgar H. Cancino # your name (or website title) here
logo: "/images/Screenshot 2023-04-16 at 16.52.34.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <small>B.S. in Robotics and Digital Systems Engineering 
  <br>Tecnológico de Monterrey (EDG, 2024)</small>
  <br><br>
  My background in data science and machine learning is both academic and self-taught. 
  <br>
  I have completed various courses and projects in these fields, for school, work and on my own initiative.
  <br><br>
  Take a look at some my most relevant projects here.
  <br><br>
  <a href="https://www.linkedin.com/in/edgar-cancino/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
