title: J. Edgar H. Cancino # your name (or website title) here
logo: "/images/pp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><big><b>About</b></big>
  <br><small>
  Robotics student with 2+ years of academic and self-taught experience in AI, DS, and ML. 
  <br>
  Business Automation Intern at Steelcase Inc. (April, 2022 - October, 2023)
  <p style="margin: 0;"><big><b>Programming languages</b></big></p>
   <ul style="margin-top: 0;">
   <li>Python: Experienced (3+ years)</li>
   <li>C++: Advanced  (3+ years)</li>
   <li>C: Proficient  (2+ years)</li>
   <li>Matlab: Proficient  (2+ years)</li>
   </ul>
   </small>
   <a href="https://edgarcancinoe.github.io/pdf/Jose_Hernandez_Resume.pdf">View My Resume</a>  
   <br><br>
  <a href="https://www.linkedin.com/in/edgar-cancino/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
